In [2]:
import numpy as np
a = np.array([[0,1,2,3],[4,5,6,7],[8,9,10,11]])
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [3]:
a.dtype


dtype('int64')

In [4]:
a[1,2]

6

In [5]:
a[:,1:3]


array([[ 1,  2],
       [ 5,  6],
       [ 9, 10]])

In [6]:
a.ndim


2

In [7]:
a.shape   


(3, 4)

In [8]:
a.strides 


(32, 8)

In [9]:
b = a.reshape(4, 3)
b

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [10]:
# reshape操作产生的是view视图，只是对数据的解释方式发生变化，数据物理地址相同
a.ctypes.data


140666048178256

In [11]:
b.ctypes.data


140666048178256

In [12]:
id(a) == id(b)


False

In [13]:
# 数据在内存中连续存储
from ctypes import string_at
string_at(b.ctypes.data, b.nbytes).hex()


'00000000000000000100000000000000020000000000000003000000000000000400000000000000050000000000000006000000000000000700000000000000080000000000000009000000000000000a000000000000000b00000000000000'

In [14]:
# b的转置c，c仍共享相同的数据block，只改变了数据的解释方式，“以列优先的方式解释行优先的存储”
c = b.T
c

array([[ 0,  3,  6,  9],
       [ 1,  4,  7, 10],
       [ 2,  5,  8, 11]])

In [15]:
c.ctypes.data


140666048178256

In [24]:
string_at(c.ctypes.data, c.nbytes).hex()


'00000000000000000100000000000000020000000000000003000000000000000400000000000000050000000000000006000000000000000700000000000000080000000000000009000000000000000a000000000000000b00000000000000'

In [17]:
a


array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [18]:
# copy会复制一份新的数据，其物理地址位于不同的区域
c = b.copy()
c


array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [19]:
c.ctypes.data


140666046206656

In [20]:
string_at(c.ctypes.data, c.nbytes).hex()


'00000000000000000100000000000000020000000000000003000000000000000400000000000000050000000000000006000000000000000700000000000000080000000000000009000000000000000a000000000000000b00000000000000'

In [21]:
# slice操作产生的也是view视图，仍指向原来数据block中的物理地址
d = b[1:3, :]
d


array([[3, 4, 5],
       [6, 7, 8]])

In [22]:
d.ctypes.data


140666048178280

In [23]:
print('data buff address from {0} to {1}'.format(b.ctypes.data, b.ctypes.data + b.nbytes))


data buff address from 140666048178256 to 140666048178352
